### ISSUE TITLE
`Email` and `Phone` validation doesn't take precedence over custom validation

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#3379]
### Describe the bug

When selecting `Email` and `Phone` validation the validation still uses the custom regular expression pattern that has been added.

![Camunda_Modeler_oZASgCCYPa](https://user-images.githubusercontent.com/7633572/210979092-45a8b760-2daf-4cdd-bdf4-c94f94e4026d.gif)

### Steps to reproduce

1. Add a _Regular expression pattern_
2. Select _Regular expression validation_ other than _Custom_
3. _Regular expression pattern_ is still used for validation

### Expected behavior

`Email` and `Phone` validation takes precedence over custom validation. Looking at the properties panel you would expect this behavior since the _Regular expression pattern_ is hidden and can't be changed.

### Environment

- Camunda Modeler Version: 5.7.0-rc.1

### Additional context

In the [`Validator`](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-viewer/src/core/Validator.js#L65) the `validationType` doesn't take precedence over the custom `pattern`.

**Comment by pinussilvestrus** [comment]
Fixed upstream via https://github.com/bpmn-io/form-js/pull/485

**Comment by nikku** [comment]
This is only partially fixed as it looks like. Once I selected email validation I cannot switch back to custom validation:

![capture eaLW0O_optimized](https://user-images.githubusercontent.com/58601/216346561-5048244b-c7b3-4b13-8009-d05dc636bd09.gif)
