### ISSUE TITLE
Resolver suggests not yet defined variables

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3510]
### Describe the bug

Right now completion suggests the variable that I'm currently writing, and other variables that may not yet have been written to me:

![image](https://user-images.githubusercontent.com/58601/225289775-28b378c6-928e-4b2e-bb47-2146264dca0f.png)

### Steps to reproduce

1. Open [`test.bpmn`](https://github.com/bpmn-io/variable-resolver/files/10978847/test.bpmn.txt)
1. Select task
2. Complete on input variables `foo` and `bar`
3. See that the variable itself, but also the variable that has not been written yet (`bar` if you complete on `foo`) is suggested

### Expected behavior

Only actually available variables are completed.

### Environment

- OS: any
- Camunda Modeler Version: 5.9.0
- Execution Platform: Camunda Cloud
- Installed plug-ins: None

**Comment by nikku** [comment]
@marstamm Is this something we would want to address (locally) in the next iteration of our tooling?

**Comment by marstamm** [comment]
I'm all for picking this up, as it is confusing to the user.

However, this is not as trivial as hiding variable names defined in the Task, as loops can be present in bpmn diagrams:

![image](https://user-images.githubusercontent.com/21984219/228216674-b1e45213-cfe9-4218-b29a-b4eb9d6471f4.png)

In these cases, it is unclear if the variable is already defined or not. If we want to deviate from just using the variable scope as defined in the bpmn-spec, we should have a proper discussion about what the behavior should be

**Comment by nikku** [comment]
@marstamm Moved to backlog as you suggested this is [not an easy pick](https://github.com/camunda/camunda-modeler/issues/3510#issuecomment-1486661942).

**Comment by marstamm** [comment]
Considering our overall strategy of "Suggest less and only what's safe", I think we can revisit this one for a more user friendly but not 100% correct fix:
- If the variable is written to in the current element, filter it out if it was not written to already (in this element)

E.g., respect the output ordering for the local scope and do not care about global variables
![image](https://user-images.githubusercontent.com/21984219/233140878-c5a5893a-a019-492d-8728-8f10dc63d0d1.png)

This would lead to less confusion. Note that this would create some cases where we either suggest too much or too little:
- Variables first written in a later Task are still suggested
- overwrite of existing variables (`foo = foo + 5`) would not suggest foo. We still show it when there are multiple sources for `foo`, but that again leads to weird behavior when working with loops

Still, I think this could get rid of some confusion when getting the variable name you are currently writing to suggested

**Comment by marstamm** [comment]
Given https://github.com/camunda/camunda-modeler/issues/3510#issuecomment-1515049606, I feel confident that we can improve the user experience, even when are not 100% correct for all cases. Moving to ready

**Comment by nikku** [comment]
Fixed upstream via https://github.com/camunda/camunda-bpmn-js/pull/277.

**Comment by marstamm** [comment]
Just noticed that this is still a problem in 5.16.0, reopening

![image](https://github.com/camunda/camunda-modeler/assets/21984219/49216d67-57f5-421b-bb31-324a15ef8bb1)

**Comment by barmac** [comment]
Since it wasn't fixed properly in the milestone M65, I moved it to the current M70.
