### ISSUE TITLE
Use of arrow keys in save dialog moves canvas on MacOS

### ISSUE THREAD

**Issue by hinsencamp** [camunda/camunda-modeler#813]
Given
I use the modeler on MacOS.

When
I open the saving dialog and use the arrow keys to move within the filename input.

Then
I move the canvas.

**Comment by nikku** [comment]
This should be fixed in `v1.15.1`. Could you verify this?

**Comment by fh48** [comment]
I tested it again with v1.15.1 - unfortunately I can still reproduce the bug.

**Comment by benhoffmann** [comment]
You can get even worse behaviour with this bug. Try to remove parts of the file name in the save dialogue while you have model elements selected - this will delete stuff in your model. 

The problem is also present in the export image dialogue.

![sep -07-2018 11-16-05](https://user-images.githubusercontent.com/17595149/45210310-836fa680-b28f-11e8-91d0-8ef079ad7d18.gif)

Recorded with 2.0.1

**Comment by philippfromme** [comment]
Ooops. 💩

**Comment by nikku** [comment]
Is this still an issue with [`v3.0.0-beta2`](https://camunda.org/release/camunda-modeler/3.0.0-beta.2/)?

**Comment by benhoffmann** [comment]
I cannot reproduce the problem with the arrow keys, but deleting stuff from within the save dialogue persists.

**Comment by nikku** [comment]
Thanks for the feedback :heart:

**Comment by jarekdanielak** [comment]
This was fixed in v5.30 with the upgrade to [bpmn-js@18](https://github.com/bpmn-io/bpmn-js/releases/tag/v18.0.0).
